services:
  backend:
    build:
      context: backend
    command: ["npm", "run", "dev"]
    depends_on:
      - mongodb
      - redis
    restart: always
    volumes:
      - ./backend/src:/backend/src

  frontend:
    build:
      context: frontend
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
    restart: always
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public

  mongodb:
    image: mongo:6
    restart: always
    volumes:
      - ./db:/data/db

  redis:
    image: redis:6
    restart: always
    volumes:
      - ./redis:/data

  nginx:
    image: nginx:1.19.6
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - backend
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
